org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=false
org.gradle.jvmargs=-Xmx4g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

mod_version=6.3.7
minecraft_version=1.21.1
neoforge_version=21.1.228
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

mod_website_link=https://www.curseforge.com/minecraft/mc-mods/mine-and-slash-reloaded
mod_issues_link=https://github.com/RobertSkalko/Mine-And-Slash-Rework/issues
mod_display_name=Mine and Slash
mod_archive_name=Mine_and_Slash
mod_id=mmorpg
curse_id=306575
modrinth_id=oifKCkhG
release_type=release
maven_group=com.robertx22

exile_library_version=2.1.3
curios_version=9.5.1+1.21.1
jei_version=19.27.0.340
player_animator_version=2.0.4+1.21.1
dungeon_realm_version=1.1.3
the_harvest_version=1.1.1
