pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'Mine-And-Slash-Rework'

include 'library_of_exile'
include 'dungeon_realm'
include 'the_harvest'
include 'ancient_obelisks'

project(':library_of_exile').projectDir = file('Library-of-Exile-Rework')
project(':dungeon_realm').projectDir = file('dungeon_realm')
project(':the_harvest').projectDir = file('the_harvest')
project(':ancient_obelisks').projectDir = file('ancient_obelisks')
